/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AddOsagoRequest : IEquatable<AddOsagoRequest>
    {
        /// <summary>
        /// Gets or Sets VehicleDocumentsId
        /// </summary>
        [Required]
        [DataMember(Name = "vehicleDocumentsId", EmitDefaultValue = true)]
        public Guid VehicleDocumentsId { get; set; }

        /// <summary>
        /// Фотография ОСАГО в бинарном формате.
        /// </summary>
        /// <value>Фотография ОСАГО в бинарном формате.</value>
        [Required]
        [DataMember(Name = "photoBytes", EmitDefaultValue = false)]
        public byte[] PhotoBytes { get; set; }

        /// <summary>
        /// Дата начала действия ОСАГО.
        /// </summary>
        /// <value>Дата начала действия ОСАГО.</value>
        [Required]
        [DataMember(Name = "dateOfIssue", EmitDefaultValue = true)]
        public DateOnly DateOfIssue { get; set; }

        /// <summary>
        /// Дата окончания действия ОСАГО.
        /// </summary>
        /// <value>Дата окончания действия ОСАГО.</value>
        [Required]
        [DataMember(Name = "dateOfExpiry", EmitDefaultValue = true)]
        public DateOnly DateOfExpiry { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddOsagoRequest {\n");
            sb.Append("  VehicleDocumentsId: ").Append(VehicleDocumentsId).Append("\n");
            sb.Append("  PhotoBytes: ").Append(PhotoBytes).Append("\n");
            sb.Append("  DateOfIssue: ").Append(DateOfIssue).Append("\n");
            sb.Append("  DateOfExpiry: ").Append(DateOfExpiry).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AddOsagoRequest)obj);
        }

        /// <summary>
        /// Returns true if AddOsagoRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AddOsagoRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddOsagoRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    VehicleDocumentsId == other.VehicleDocumentsId ||
                    VehicleDocumentsId.Equals(other.VehicleDocumentsId)
                ) &&
                (
                    PhotoBytes == other.PhotoBytes ||
                    PhotoBytes != null &&
                    PhotoBytes.Equals(other.PhotoBytes)
                ) &&
                (
                    DateOfIssue == other.DateOfIssue ||
                    DateOfIssue.Equals(other.DateOfIssue)
                ) &&
                (
                    DateOfExpiry == other.DateOfExpiry ||
                    DateOfExpiry.Equals(other.DateOfExpiry)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + VehicleDocumentsId.GetHashCode();
                if (PhotoBytes != null)
                    hashCode = hashCode * 59 + PhotoBytes.GetHashCode();

                hashCode = hashCode * 59 + DateOfIssue.GetHashCode();

                hashCode = hashCode * 59 + DateOfExpiry.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(AddOsagoRequest left, AddOsagoRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AddOsagoRequest left, AddOsagoRequest right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}