/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AddPtsRequest : IEquatable<AddPtsRequest>
    {
        /// <summary>
        /// Фотография лицевой стороны ПТС в бинарном формате.
        /// </summary>
        /// <value>Фотография лицевой стороны ПТС в бинарном формате.</value>
        [Required]
        [DataMember(Name = "frontPhotoBytes", EmitDefaultValue = false)]
        public byte[] FrontPhotoBytes { get; set; }

        /// <summary>
        /// Фотография обратной стороны ПТС в бинарном формате.
        /// </summary>
        /// <value>Фотография обратной стороны ПТС в бинарном формате.</value>
        [Required]
        [DataMember(Name = "backPhotoBytes", EmitDefaultValue = false)]
        public byte[] BackPhotoBytes { get; set; }

        /// <summary>
        /// Год выпуска автомобиля.
        /// </summary>
        /// <value>Год выпуска автомобиля.</value>
        [Required]
        [DataMember(Name = "yearOfManufacture", EmitDefaultValue = true)]
        public DateTime YearOfManufacture { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [Required]
        [DataMember(Name = "color", EmitDefaultValue = true)]
        public Color Color { get; set; }

        /// <summary>
        /// VIN-номер автомобиля.
        /// </summary>
        /// <value>VIN-номер автомобиля.</value>
        [Required]
        [DataMember(Name = "vin", EmitDefaultValue = false)]
        public string Vin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddPtsRequest {\n");
            sb.Append("  FrontPhotoBytes: ").Append(FrontPhotoBytes).Append("\n");
            sb.Append("  BackPhotoBytes: ").Append(BackPhotoBytes).Append("\n");
            sb.Append("  YearOfManufacture: ").Append(YearOfManufacture).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Vin: ").Append(Vin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AddPtsRequest)obj);
        }

        /// <summary>
        /// Returns true if AddPtsRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AddPtsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddPtsRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    FrontPhotoBytes == other.FrontPhotoBytes ||
                    FrontPhotoBytes != null &&
                    FrontPhotoBytes.Equals(other.FrontPhotoBytes)
                ) &&
                (
                    BackPhotoBytes == other.BackPhotoBytes ||
                    BackPhotoBytes != null &&
                    BackPhotoBytes.Equals(other.BackPhotoBytes)
                ) &&
                (
                    YearOfManufacture == other.YearOfManufacture ||
                    YearOfManufacture.Equals(other.YearOfManufacture)
                ) &&
                (
                    Color == other.Color ||
                    Color.Equals(other.Color)
                ) &&
                (
                    Vin == other.Vin ||
                    Vin != null &&
                    Vin.Equals(other.Vin)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (FrontPhotoBytes != null)
                    hashCode = hashCode * 59 + FrontPhotoBytes.GetHashCode();
                if (BackPhotoBytes != null)
                    hashCode = hashCode * 59 + BackPhotoBytes.GetHashCode();

                hashCode = hashCode * 59 + YearOfManufacture.GetHashCode();

                hashCode = hashCode * 59 + Color.GetHashCode();
                if (Vin != null)
                    hashCode = hashCode * 59 + Vin.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(AddPtsRequest left, AddPtsRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AddPtsRequest left, AddPtsRequest right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}