/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AddStsRequest : IEquatable<AddStsRequest>
    {
        /// <summary>
        /// Фотография лицевой стороны СТС в бинарном формате.
        /// </summary>
        /// <value>Фотография лицевой стороны СТС в бинарном формате.</value>
        [Required]
        [DataMember(Name = "frontPhotoBytes", EmitDefaultValue = false)]
        public byte[] FrontPhotoBytes { get; set; }

        /// <summary>
        /// Фотография обратной стороны СТС в бинарном формате.
        /// </summary>
        /// <value>Фотография обратной стороны СТС в бинарном формате.</value>
        [Required]
        [DataMember(Name = "backPhotoBytes", EmitDefaultValue = false)]
        public byte[] BackPhotoBytes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddStsRequest {\n");
            sb.Append("  FrontPhotoBytes: ").Append(FrontPhotoBytes).Append("\n");
            sb.Append("  BackPhotoBytes: ").Append(BackPhotoBytes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AddStsRequest)obj);
        }

        /// <summary>
        /// Returns true if AddStsRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AddStsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddStsRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    FrontPhotoBytes == other.FrontPhotoBytes ||
                    FrontPhotoBytes != null &&
                    FrontPhotoBytes.Equals(other.FrontPhotoBytes)
                ) &&
                (
                    BackPhotoBytes == other.BackPhotoBytes ||
                    BackPhotoBytes != null &&
                    BackPhotoBytes.Equals(other.BackPhotoBytes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (FrontPhotoBytes != null)
                    hashCode = hashCode * 59 + FrontPhotoBytes.GetHashCode();
                if (BackPhotoBytes != null)
                    hashCode = hashCode * 59 + BackPhotoBytes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(AddStsRequest left, AddStsRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AddStsRequest left, AddStsRequest right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}