/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AddVehicleReq : IEquatable<AddVehicleReq>
    {
        /// <summary>
        /// Уникальный идентификатор модели автомобиля.
        /// </summary>
        /// <value>Уникальный идентификатор модели автомобиля.</value>
        [Required]
        [DataMember(Name = "modelId", EmitDefaultValue = true)]
        public Guid ModelId { get; set; }

        /// <summary>
        /// Государственный номер автомобиля.
        /// </summary>
        /// <value>Государственный номер автомобиля.</value>
        [Required]
        [DataMember(Name = "plateNumber", EmitDefaultValue = false)]
        public string PlateNumber { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [Required]
        [DataMember(Name = "color", EmitDefaultValue = true)]
        public Color Color { get; set; }

        /// <summary>
        /// VIN-номер автомобиля.
        /// </summary>
        /// <value>VIN-номер автомобиля.</value>
        [Required]
        [DataMember(Name = "vin", EmitDefaultValue = false)]
        public string Vin { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", EmitDefaultValue = false)]
        public Location? Location { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddVehicleReq {\n");
            sb.Append("  ModelId: ").Append(ModelId).Append("\n");
            sb.Append("  PlateNumber: ").Append(PlateNumber).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Vin: ").Append(Vin).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AddVehicleReq)obj);
        }

        /// <summary>
        /// Returns true if AddVehicleReq instances are equal
        /// </summary>
        /// <param name="other">Instance of AddVehicleReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddVehicleReq other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    ModelId == other.ModelId ||
                    ModelId.Equals(other.ModelId)
                ) &&
                (
                    PlateNumber == other.PlateNumber ||
                    PlateNumber != null &&
                    PlateNumber.Equals(other.PlateNumber)
                ) &&
                (
                    Color == other.Color ||
                    Color.Equals(other.Color)
                ) &&
                (
                    Vin == other.Vin ||
                    Vin != null &&
                    Vin.Equals(other.Vin)
                ) &&
                (
                    Location == other.Location ||
                    Location != null &&
                    Location.Equals(other.Location)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + ModelId.GetHashCode();
                if (PlateNumber != null)
                    hashCode = hashCode * 59 + PlateNumber.GetHashCode();

                hashCode = hashCode * 59 + Color.GetHashCode();
                if (Vin != null)
                    hashCode = hashCode * 59 + Vin.GetHashCode();
                if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(AddVehicleReq left, AddVehicleReq right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AddVehicleReq left, AddVehicleReq right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}