/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Тип кузова автомобиля.
    /// </summary>
    /// <value>Тип кузова автомобиля.</value>
    [TypeConverter(typeof(CustomEnumConverter<BodyType>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BodyType
    {
        /// <summary>
        /// Enum SedanEnum for sedan
        /// </summary>
        [EnumMember(Value = "sedan")] SedanEnum = 1,

        /// <summary>
        /// Enum SuvEnum for suv
        /// </summary>
        [EnumMember(Value = "suv")] SuvEnum = 2,

        /// <summary>
        /// Enum HatchbackEnum for hatchback
        /// </summary>
        [EnumMember(Value = "hatchback")] HatchbackEnum = 3,

        /// <summary>
        /// Enum CoupeEnum for coupe
        /// </summary>
        [EnumMember(Value = "coupe")] CoupeEnum = 4,

        /// <summary>
        /// Enum ConvertibleEnum for convertible
        /// </summary>
        [EnumMember(Value = "convertible")] ConvertibleEnum = 5,

        /// <summary>
        /// Enum MinivanEnum for minivan
        /// </summary>
        [EnumMember(Value = "minivan")] MinivanEnum = 6,

        /// <summary>
        /// Enum PickupEnum for pickup
        /// </summary>
        [EnumMember(Value = "pickup")] PickupEnum = 7
    }
}