/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Статус проверки.
    /// </summary>
    /// <value>Статус проверки.</value>
    [TypeConverter(typeof(CustomEnumConverter<CheckStatus>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CheckStatus
    {
        /// <summary>
        /// Enum PendingReviewEnum for pendingReview
        /// </summary>
        [EnumMember(Value = "pendingReview")] PendingReviewEnum = 1,

        /// <summary>
        /// Enum ApprovedEnum for approved
        /// </summary>
        [EnumMember(Value = "approved")] ApprovedEnum = 2,

        /// <summary>
        /// Enum RejectedEnum for rejected
        /// </summary>
        [EnumMember(Value = "rejected")] RejectedEnum = 3
    }
}