/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Цвет автомобиля
    /// </summary>
    /// <value>Цвет автомобиля</value>
    [TypeConverter(typeof(CustomEnumConverter<Color>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Color
    {
        /// <summary>
        /// Enum WhiteEnum for white
        /// </summary>
        [EnumMember(Value = "white")] WhiteEnum = 1,

        /// <summary>
        /// Enum GreyEnum for grey
        /// </summary>
        [EnumMember(Value = "grey")] GreyEnum = 2,

        /// <summary>
        /// Enum BlackEnum for black
        /// </summary>
        [EnumMember(Value = "black")] BlackEnum = 3,

        /// <summary>
        /// Enum BlueEnum for blue
        /// </summary>
        [EnumMember(Value = "blue")] BlueEnum = 4,

        /// <summary>
        /// Enum RedEnum for red
        /// </summary>
        [EnumMember(Value = "red")] RedEnum = 5,

        /// <summary>
        /// Enum YellowEnum for yellow
        /// </summary>
        [EnumMember(Value = "yellow")] YellowEnum = 6,

        /// <summary>
        /// Enum OrangeEnum for orange
        /// </summary>
        [EnumMember(Value = "orange")] OrangeEnum = 7,

        /// <summary>
        /// Enum GreenEnum for green
        /// </summary>
        [EnumMember(Value = "green")] GreenEnum = 8,

        /// <summary>
        /// Enum BeigeEnum for beige
        /// </summary>
        [EnumMember(Value = "beige")] BeigeEnum = 9
    }
}