/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Статус водительского удостоверения.
    /// </summary>
    /// <value>Статус водительского удостоверения.</value>
    [TypeConverter(typeof(CustomEnumConverter<DrivingLicenseStatus>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DrivingLicenseStatus
    {
        /// <summary>
        /// Enum PendingPhotosAddingEnum for pendingPhotosAdding
        /// </summary>
        [EnumMember(Value = "pendingPhotosAdding")]
        PendingPhotosAddingEnum = 1,

        /// <summary>
        /// Enum PendingProcessingEnum for pendingProcessing
        /// </summary>
        [EnumMember(Value = "pendingProcessing")]
        PendingProcessingEnum = 2,

        /// <summary>
        /// Enum ApprovedEnum for approved
        /// </summary>
        [EnumMember(Value = "approved")] ApprovedEnum = 3,

        /// <summary>
        /// Enum RejectedEnum for rejected
        /// </summary>
        [EnumMember(Value = "rejected")] RejectedEnum = 4,

        /// <summary>
        /// Enum ExpiredEnum for expired
        /// </summary>
        [EnumMember(Value = "expired")] ExpiredEnum = 5
    }
}