/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DrivingLicense : IEquatable<DrivingLicense>
    {
        /// <summary>
        /// Уникальный идентификатор водительского удостоверения.
        /// </summary>
        /// <value>Уникальный идентификатор водительского удостоверения.</value>
        [Required]
        [DataMember(Name = "licenseId", EmitDefaultValue = true)]
        public Guid LicenseId { get; set; }

        /// <summary>
        /// Уникальный идентификатор работника, которому принадлежит удостоверение.
        /// </summary>
        /// <value>Уникальный идентификатор работника, которому принадлежит удостоверение.</value>
        [Required]
        [DataMember(Name = "customerId", EmitDefaultValue = true)]
        public Guid CustomerId { get; set; }

        /// <summary>
        /// Номер водительского удостоверения.
        /// </summary>
        /// <value>Номер водительского удостоверения.</value>
        [Required]
        [DataMember(Name = "licenseNumber", EmitDefaultValue = false)]
        public string LicenseNumber { get; set; }

        /// <summary>
        /// Дата выдачи водительского удостоверения.
        /// </summary>
        /// <value>Дата выдачи водительского удостоверения.</value>
        [Required]
        [DataMember(Name = "issueDate", EmitDefaultValue = true)]
        public DateOnly IssueDate { get; set; }

        /// <summary>
        /// Дата окончания срока действия водительского удостоверения.
        /// </summary>
        /// <value>Дата окончания срока действия водительского удостоверения.</value>
        [Required]
        [DataMember(Name = "expiryDate", EmitDefaultValue = true)]
        public DateOnly ExpiryDate { get; set; }

        /// <summary>
        /// Список категорий вождения.
        /// </summary>
        /// <value>Список категорий вождения.</value>
        [Required]
        [DataMember(Name = "drivingCategories", EmitDefaultValue = false)]
        public List<string> DrivingCategories { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public DrivingLicenseStatus Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DrivingLicense {\n");
            sb.Append("  LicenseId: ").Append(LicenseId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  LicenseNumber: ").Append(LicenseNumber).Append("\n");
            sb.Append("  IssueDate: ").Append(IssueDate).Append("\n");
            sb.Append("  ExpiryDate: ").Append(ExpiryDate).Append("\n");
            sb.Append("  DrivingCategories: ").Append(DrivingCategories).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DrivingLicense)obj);
        }

        /// <summary>
        /// Returns true if DrivingLicense instances are equal
        /// </summary>
        /// <param name="other">Instance of DrivingLicense to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DrivingLicense other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    LicenseId == other.LicenseId ||
                    LicenseId.Equals(other.LicenseId)
                ) &&
                (
                    CustomerId == other.CustomerId ||
                    CustomerId.Equals(other.CustomerId)
                ) &&
                (
                    LicenseNumber == other.LicenseNumber ||
                    LicenseNumber != null &&
                    LicenseNumber.Equals(other.LicenseNumber)
                ) &&
                (
                    IssueDate == other.IssueDate ||
                    IssueDate.Equals(other.IssueDate)
                ) &&
                (
                    ExpiryDate == other.ExpiryDate ||
                    ExpiryDate.Equals(other.ExpiryDate)
                ) &&
                (
                    DrivingCategories == other.DrivingCategories ||
                    DrivingCategories != null &&
                    other.DrivingCategories != null &&
                    DrivingCategories.SequenceEqual(other.DrivingCategories)
                ) &&
                (
                    Status == other.Status ||
                    Status.Equals(other.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + LicenseId.GetHashCode();

                hashCode = hashCode * 59 + CustomerId.GetHashCode();
                if (LicenseNumber != null)
                    hashCode = hashCode * 59 + LicenseNumber.GetHashCode();

                hashCode = hashCode * 59 + IssueDate.GetHashCode();

                hashCode = hashCode * 59 + ExpiryDate.GetHashCode();
                if (DrivingCategories != null)
                    hashCode = hashCode * 59 + DrivingCategories.GetHashCode();

                hashCode = hashCode * 59 + Status.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(DrivingLicense left, DrivingLicense right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DrivingLicense left, DrivingLicense right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}