/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Fixation : IEquatable<Fixation>
    {
        /// <summary>
        /// URL изображения повреждения в S3 хранилище.
        /// </summary>
        /// <value>URL изображения повреждения в S3 хранилище.</value>
        [Required]
        [DataMember(Name = "s3Url", EmitDefaultValue = false)]
        public string S3Url { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [Required]
        [DataMember(Name = "category", EmitDefaultValue = true)]
        public FixationCategory Category { get; set; }

        /// <summary>
        /// Описание повреждения.
        /// </summary>
        /// <value>Описание повреждения.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string? Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Fixation {\n");
            sb.Append("  S3Url: ").Append(S3Url).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Fixation)obj);
        }

        /// <summary>
        /// Returns true if Fixation instances are equal
        /// </summary>
        /// <param name="other">Instance of Fixation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Fixation other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    S3Url == other.S3Url ||
                    S3Url != null &&
                    S3Url.Equals(other.S3Url)
                ) &&
                (
                    Category == other.Category ||
                    Category.Equals(other.Category)
                ) &&
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (S3Url != null)
                    hashCode = hashCode * 59 + S3Url.GetHashCode();

                hashCode = hashCode * 59 + Category.GetHashCode();
                if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(Fixation left, Fixation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Fixation left, Fixation right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}