/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Категория повреждения автомобиля.
    /// </summary>
    /// <value>Категория повреждения автомобиля.</value>
    [TypeConverter(typeof(CustomEnumConverter<FixationCategory>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FixationCategory
    {
        /// <summary>
        /// Enum MinorDamageEnum for minorDamage
        /// </summary>
        [EnumMember(Value = "minorDamage")] MinorDamageEnum = 1,

        /// <summary>
        /// Enum SignificantDamageEnum for significantDamage
        /// </summary>
        [EnumMember(Value = "significantDamage")]
        SignificantDamageEnum = 2
    }
}