/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Тип топлива автомобиля.
    /// </summary>
    /// <value>Тип топлива автомобиля.</value>
    [TypeConverter(typeof(CustomEnumConverter<FuelType>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FuelType
    {
        /// <summary>
        /// Enum GasolineEnum for gasoline
        /// </summary>
        [EnumMember(Value = "gasoline")] GasolineEnum = 1,

        /// <summary>
        /// Enum DieselEnum for diesel
        /// </summary>
        [EnumMember(Value = "diesel")] DieselEnum = 2,

        /// <summary>
        /// Enum ElectricEnum for electric
        /// </summary>
        [EnumMember(Value = "electric")] ElectricEnum = 3,

        /// <summary>
        /// Enum HybridEnum for hybrid
        /// </summary>
        [EnumMember(Value = "hybrid")] HybridEnum = 4
    }
}