/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetAllModelsRes : IEquatable<GetAllModelsRes>
    {
        /// <summary>
        /// Список всех моделей автомобилей.
        /// </summary>
        /// <value>Список всех моделей автомобилей.</value>
        [Required]
        [DataMember(Name = "models", EmitDefaultValue = false)]
        public List<ModelShortView> Models { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetAllModelsRes {\n");
            sb.Append("  Models: ").Append(Models).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetAllModelsRes)obj);
        }

        /// <summary>
        /// Returns true if GetAllModelsRes instances are equal
        /// </summary>
        /// <param name="other">Instance of GetAllModelsRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetAllModelsRes other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
            (
                Models == other.Models ||
                Models != null &&
                other.Models != null &&
                Models.SequenceEqual(other.Models)
            );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Models != null)
                    hashCode = hashCode * 59 + Models.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(GetAllModelsRes left, GetAllModelsRes right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetAllModelsRes left, GetAllModelsRes right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}