/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetModelByIdRes : IEquatable<GetModelByIdRes>
    {
        /// <summary>
        /// Уникальный идентификатор модели.
        /// </summary>
        /// <value>Уникальный идентификатор модели.</value>
        [Required]
        [DataMember(Name = "modelId", EmitDefaultValue = true)]
        public Guid ModelId { get; set; }

        /// <summary>
        /// Марка автомобиля.
        /// </summary>
        /// <value>Марка автомобиля.</value>
        [Required]
        [DataMember(Name = "brand", EmitDefaultValue = false)]
        public string Brand { get; set; }

        /// <summary>
        /// Название модели автомобиля.
        /// </summary>
        /// <value>Название модели автомобиля.</value>
        [Required]
        [DataMember(Name = "carModel", EmitDefaultValue = false)]
        public string CarModel { get; set; }

        /// <summary>
        /// Категория автомобиля.
        /// </summary>
        /// <value>Категория автомобиля.</value>
        [Required]
        [DataMember(Name = "category", EmitDefaultValue = false)]
        public string Category { get; set; }

        /// <summary>
        /// Стоимость аренды за минуту.
        /// </summary>
        /// <value>Стоимость аренды за минуту.</value>
        [Required]
        [DataMember(Name = "pricePerMin", EmitDefaultValue = true)]
        public double PricePerMin { get; set; }

        /// <summary>
        /// Стоимость аренды за час.
        /// </summary>
        /// <value>Стоимость аренды за час.</value>
        [Required]
        [DataMember(Name = "pricePerHour", EmitDefaultValue = true)]
        public double PricePerHour { get; set; }

        /// <summary>
        /// Стоимость аренды за день.
        /// </summary>
        /// <value>Стоимость аренды за день.</value>
        [Required]
        [DataMember(Name = "pricePerDay", EmitDefaultValue = true)]
        public double PricePerDay { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetModelByIdRes {\n");
            sb.Append("  ModelId: ").Append(ModelId).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  CarModel: ").Append(CarModel).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  PricePerMin: ").Append(PricePerMin).Append("\n");
            sb.Append("  PricePerHour: ").Append(PricePerHour).Append("\n");
            sb.Append("  PricePerDay: ").Append(PricePerDay).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetModelByIdRes)obj);
        }

        /// <summary>
        /// Returns true if GetModelByIdRes instances are equal
        /// </summary>
        /// <param name="other">Instance of GetModelByIdRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetModelByIdRes other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    ModelId == other.ModelId ||
                    ModelId.Equals(other.ModelId)
                ) &&
                (
                    Brand == other.Brand ||
                    Brand != null &&
                    Brand.Equals(other.Brand)
                ) &&
                (
                    CarModel == other.CarModel ||
                    CarModel != null &&
                    CarModel.Equals(other.CarModel)
                ) &&
                (
                    Category == other.Category ||
                    Category != null &&
                    Category.Equals(other.Category)
                ) &&
                (
                    PricePerMin == other.PricePerMin ||
                    PricePerMin.Equals(other.PricePerMin)
                ) &&
                (
                    PricePerHour == other.PricePerHour ||
                    PricePerHour.Equals(other.PricePerHour)
                ) &&
                (
                    PricePerDay == other.PricePerDay ||
                    PricePerDay.Equals(other.PricePerDay)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + ModelId.GetHashCode();
                if (Brand != null)
                    hashCode = hashCode * 59 + Brand.GetHashCode();
                if (CarModel != null)
                    hashCode = hashCode * 59 + CarModel.GetHashCode();
                if (Category != null)
                    hashCode = hashCode * 59 + Category.GetHashCode();

                hashCode = hashCode * 59 + PricePerMin.GetHashCode();

                hashCode = hashCode * 59 + PricePerHour.GetHashCode();

                hashCode = hashCode * 59 + PricePerDay.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(GetModelByIdRes left, GetModelByIdRes right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetModelByIdRes left, GetModelByIdRes right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}