/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetOsagoByVehicleDocumentsIdResponse : IEquatable<GetOsagoByVehicleDocumentsIdResponse>
    {
        /// <summary>
        /// URL фотографии ОСАГО в хранилище S3.
        /// </summary>
        /// <value>URL фотографии ОСАГО в хранилище S3.</value>
        [Required]
        [DataMember(Name = "photoS3Url", EmitDefaultValue = false)]
        public string PhotoS3Url { get; set; }

        /// <summary>
        /// Gets or Sets OsagoStatus
        /// </summary>
        [Required]
        [DataMember(Name = "osagoStatus", EmitDefaultValue = true)]
        public OsagoStatus OsagoStatus { get; set; }

        /// <summary>
        /// Серия ОСАГО.
        /// </summary>
        /// <value>Серия ОСАГО.</value>
        [Required]
        [DataMember(Name = "dateOfIssue", EmitDefaultValue = true)]
        public DateOnly DateOfIssue { get; set; }

        /// <summary>
        /// Дата окончания действия ОСАГО.
        /// </summary>
        /// <value>Дата окончания действия ОСАГО.</value>
        [Required]
        [DataMember(Name = "dateOfExpiry", EmitDefaultValue = true)]
        public DateOnly DateOfExpiry { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetOsagoByVehicleDocumentsIdResponse {\n");
            sb.Append("  PhotoS3Url: ").Append(PhotoS3Url).Append("\n");
            sb.Append("  OsagoStatus: ").Append(OsagoStatus).Append("\n");
            sb.Append("  DateOfIssue: ").Append(DateOfIssue).Append("\n");
            sb.Append("  DateOfExpiry: ").Append(DateOfExpiry).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetOsagoByVehicleDocumentsIdResponse)obj);
        }

        /// <summary>
        /// Returns true if GetOsagoByVehicleDocumentsIdResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GetOsagoByVehicleDocumentsIdResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetOsagoByVehicleDocumentsIdResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    PhotoS3Url == other.PhotoS3Url ||
                    PhotoS3Url != null &&
                    PhotoS3Url.Equals(other.PhotoS3Url)
                ) &&
                (
                    OsagoStatus == other.OsagoStatus ||
                    OsagoStatus.Equals(other.OsagoStatus)
                ) &&
                (
                    DateOfIssue == other.DateOfIssue ||
                    DateOfIssue.Equals(other.DateOfIssue)
                ) &&
                (
                    DateOfExpiry == other.DateOfExpiry ||
                    DateOfExpiry.Equals(other.DateOfExpiry)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (PhotoS3Url != null)
                    hashCode = hashCode * 59 + PhotoS3Url.GetHashCode();

                hashCode = hashCode * 59 + OsagoStatus.GetHashCode();

                hashCode = hashCode * 59 + DateOfIssue.GetHashCode();

                hashCode = hashCode * 59 + DateOfExpiry.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(
            GetOsagoByVehicleDocumentsIdResponse left,
            GetOsagoByVehicleDocumentsIdResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(
            GetOsagoByVehicleDocumentsIdResponse left,
            GetOsagoByVehicleDocumentsIdResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}