/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetPtsByVehicleDocumentsIdResponse : IEquatable<GetPtsByVehicleDocumentsIdResponse>
    {
        /// <summary>
        /// URL фотографии лицевой стороны ПТС в хранилище S3.
        /// </summary>
        /// <value>URL фотографии лицевой стороны ПТС в хранилище S3.</value>
        [Required]
        [DataMember(Name = "frontPhotoS3Url", EmitDefaultValue = false)]
        public string FrontPhotoS3Url { get; set; }

        /// <summary>
        /// URL фотографии обратной стороны ПТС в хранилище S3.
        /// </summary>
        /// <value>URL фотографии обратной стороны ПТС в хранилище S3.</value>
        [Required]
        [DataMember(Name = "backPhotoS3Url", EmitDefaultValue = false)]
        public string BackPhotoS3Url { get; set; }

        /// <summary>
        /// Год выпуска автомобиля.
        /// </summary>
        /// <value>Год выпуска автомобиля.</value>
        [Required]
        [DataMember(Name = "yearOfManufacture", EmitDefaultValue = true)]
        public DateTime YearOfManufacture { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [Required]
        [DataMember(Name = "color", EmitDefaultValue = true)]
        public Color Color { get; set; }

        /// <summary>
        /// VIN-номер автомобиля.
        /// </summary>
        /// <value>VIN-номер автомобиля.</value>
        [Required]
        [DataMember(Name = "vin", EmitDefaultValue = false)]
        public string Vin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetPtsByVehicleDocumentsIdResponse {\n");
            sb.Append("  FrontPhotoS3Url: ").Append(FrontPhotoS3Url).Append("\n");
            sb.Append("  BackPhotoS3Url: ").Append(BackPhotoS3Url).Append("\n");
            sb.Append("  YearOfManufacture: ").Append(YearOfManufacture).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Vin: ").Append(Vin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetPtsByVehicleDocumentsIdResponse)obj);
        }

        /// <summary>
        /// Returns true if GetPtsByVehicleDocumentsIdResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GetPtsByVehicleDocumentsIdResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetPtsByVehicleDocumentsIdResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    FrontPhotoS3Url == other.FrontPhotoS3Url ||
                    FrontPhotoS3Url != null &&
                    FrontPhotoS3Url.Equals(other.FrontPhotoS3Url)
                ) &&
                (
                    BackPhotoS3Url == other.BackPhotoS3Url ||
                    BackPhotoS3Url != null &&
                    BackPhotoS3Url.Equals(other.BackPhotoS3Url)
                ) &&
                (
                    YearOfManufacture == other.YearOfManufacture ||
                    YearOfManufacture.Equals(other.YearOfManufacture)
                ) &&
                (
                    Color == other.Color ||
                    Color.Equals(other.Color)
                ) &&
                (
                    Vin == other.Vin ||
                    Vin != null &&
                    Vin.Equals(other.Vin)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (FrontPhotoS3Url != null)
                    hashCode = hashCode * 59 + FrontPhotoS3Url.GetHashCode();
                if (BackPhotoS3Url != null)
                    hashCode = hashCode * 59 + BackPhotoS3Url.GetHashCode();

                hashCode = hashCode * 59 + YearOfManufacture.GetHashCode();

                hashCode = hashCode * 59 + Color.GetHashCode();
                if (Vin != null)
                    hashCode = hashCode * 59 + Vin.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(
            GetPtsByVehicleDocumentsIdResponse left,
            GetPtsByVehicleDocumentsIdResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(
            GetPtsByVehicleDocumentsIdResponse left,
            GetPtsByVehicleDocumentsIdResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}