/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetStsByVehicleDocumentsIdResponse : IEquatable<GetStsByVehicleDocumentsIdResponse>
    {
        /// <summary>
        /// URL фотографии лицевой стороны СТС в хранилище S3.
        /// </summary>
        /// <value>URL фотографии лицевой стороны СТС в хранилище S3.</value>
        [Required]
        [DataMember(Name = "frontPhotoS3Url", EmitDefaultValue = false)]
        public string FrontPhotoS3Url { get; set; }

        /// <summary>
        /// URL фотографии обратной стороны СТС в хранилище S3.
        /// </summary>
        /// <value>URL фотографии обратной стороны СТС в хранилище S3.</value>
        [Required]
        [DataMember(Name = "backPhotoS3Url", EmitDefaultValue = false)]
        public string BackPhotoS3Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetStsByVehicleDocumentsIdResponse {\n");
            sb.Append("  FrontPhotoS3Url: ").Append(FrontPhotoS3Url).Append("\n");
            sb.Append("  BackPhotoS3Url: ").Append(BackPhotoS3Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetStsByVehicleDocumentsIdResponse)obj);
        }

        /// <summary>
        /// Returns true if GetStsByVehicleDocumentsIdResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GetStsByVehicleDocumentsIdResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetStsByVehicleDocumentsIdResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    FrontPhotoS3Url == other.FrontPhotoS3Url ||
                    FrontPhotoS3Url != null &&
                    FrontPhotoS3Url.Equals(other.FrontPhotoS3Url)
                ) &&
                (
                    BackPhotoS3Url == other.BackPhotoS3Url ||
                    BackPhotoS3Url != null &&
                    BackPhotoS3Url.Equals(other.BackPhotoS3Url)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (FrontPhotoS3Url != null)
                    hashCode = hashCode * 59 + FrontPhotoS3Url.GetHashCode();
                if (BackPhotoS3Url != null)
                    hashCode = hashCode * 59 + BackPhotoS3Url.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(
            GetStsByVehicleDocumentsIdResponse left,
            GetStsByVehicleDocumentsIdResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(
            GetStsByVehicleDocumentsIdResponse left,
            GetStsByVehicleDocumentsIdResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}