/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetVehicleDocumentsByVehicleIdResponse : IEquatable<GetVehicleDocumentsByVehicleIdResponse>
    {
        /// <summary>
        /// Уникальный идентификатор комплекта документов на автомобиль.
        /// </summary>
        /// <value>Уникальный идентификатор комплекта документов на автомобиль.</value>
        [Required]
        [DataMember(Name = "vehicleDocumentsId", EmitDefaultValue = true)]
        public Guid VehicleDocumentsId { get; set; }

        /// <summary>
        /// Уникальный идентификатор автомобиля.
        /// </summary>
        /// <value>Уникальный идентификатор автомобиля.</value>
        [Required]
        [DataMember(Name = "vehicleId", EmitDefaultValue = true)]
        public Guid VehicleId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public GetVehicleDocumentsByVehicleIdResponseStatus Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetVehicleDocumentsByVehicleIdResponse {\n");
            sb.Append("  VehicleDocumentsId: ").Append(VehicleDocumentsId).Append("\n");
            sb.Append("  VehicleId: ").Append(VehicleId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetVehicleDocumentsByVehicleIdResponse)obj);
        }

        /// <summary>
        /// Returns true if GetVehicleDocumentsByVehicleIdResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GetVehicleDocumentsByVehicleIdResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetVehicleDocumentsByVehicleIdResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    VehicleDocumentsId == other.VehicleDocumentsId ||
                    VehicleDocumentsId.Equals(other.VehicleDocumentsId)
                ) &&
                (
                    VehicleId == other.VehicleId ||
                    VehicleId.Equals(other.VehicleId)
                ) &&
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + VehicleDocumentsId.GetHashCode();

                hashCode = hashCode * 59 + VehicleId.GetHashCode();
                if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(
            GetVehicleDocumentsByVehicleIdResponse left,
            GetVehicleDocumentsByVehicleIdResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(
            GetVehicleDocumentsByVehicleIdResponse left,
            GetVehicleDocumentsByVehicleIdResponse right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}