/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetVehiclesInSquareReq : IEquatable<GetVehiclesInSquareReq>
    {
        /// <summary>
        /// Gets or Sets FilteringStatus
        /// </summary>
        [Required]
        [DataMember(Name = "filteringStatus", EmitDefaultValue = true)]
        public Status FilteringStatus { get; set; }

        /// <summary>
        /// Gets or Sets UpperLeftLocation
        /// </summary>
        [Required]
        [DataMember(Name = "upperLeftLocation", EmitDefaultValue = false)]
        public Location UpperLeftLocation { get; set; }

        /// <summary>
        /// Gets or Sets LowerRightLocation
        /// </summary>
        [Required]
        [DataMember(Name = "lowerRightLocation", EmitDefaultValue = false)]
        public Location LowerRightLocation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetVehiclesInSquareReq {\n");
            sb.Append("  FilteringStatus: ").Append(FilteringStatus).Append("\n");
            sb.Append("  UpperLeftLocation: ").Append(UpperLeftLocation).Append("\n");
            sb.Append("  LowerRightLocation: ").Append(LowerRightLocation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetVehiclesInSquareReq)obj);
        }

        /// <summary>
        /// Returns true if GetVehiclesInSquareReq instances are equal
        /// </summary>
        /// <param name="other">Instance of GetVehiclesInSquareReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetVehiclesInSquareReq other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    FilteringStatus == other.FilteringStatus ||
                    FilteringStatus.Equals(other.FilteringStatus)
                ) &&
                (
                    UpperLeftLocation == other.UpperLeftLocation ||
                    UpperLeftLocation != null &&
                    UpperLeftLocation.Equals(other.UpperLeftLocation)
                ) &&
                (
                    LowerRightLocation == other.LowerRightLocation ||
                    LowerRightLocation != null &&
                    LowerRightLocation.Equals(other.LowerRightLocation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + FilteringStatus.GetHashCode();
                if (UpperLeftLocation != null)
                    hashCode = hashCode * 59 + UpperLeftLocation.GetHashCode();
                if (LowerRightLocation != null)
                    hashCode = hashCode * 59 + LowerRightLocation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(GetVehiclesInSquareReq left, GetVehiclesInSquareReq right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetVehiclesInSquareReq left, GetVehiclesInSquareReq right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}