/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class
        GetVehicleDocumentsByVehicleIdResponseStatus : IEquatable<GetVehicleDocumentsByVehicleIdResponseStatus>
    {
        /// <summary>
        /// Наличие ПТС.
        /// </summary>
        /// <value>Наличие ПТС.</value>
        [Required]
        [DataMember(Name = "isPtsAdded", EmitDefaultValue = true)]
        public bool IsPtsAdded { get; set; }

        /// <summary>
        /// Наличие СТС.
        /// </summary>
        /// <value>Наличие СТС.</value>
        [Required]
        [DataMember(Name = "isStsAdded", EmitDefaultValue = true)]
        public bool IsStsAdded { get; set; }

        /// <summary>
        /// Наличие ОСАГО.
        /// </summary>
        /// <value>Наличие ОСАГО.</value>
        [Required]
        [DataMember(Name = "isOsagoAdded", EmitDefaultValue = true)]
        public bool IsOsagoAdded { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetVehicleDocumentsByVehicleIdResponseStatus {\n");
            sb.Append("  IsPtsAdded: ").Append(IsPtsAdded).Append("\n");
            sb.Append("  IsStsAdded: ").Append(IsStsAdded).Append("\n");
            sb.Append("  IsOsagoAdded: ").Append(IsOsagoAdded).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetVehicleDocumentsByVehicleIdResponseStatus)obj);
        }

        /// <summary>
        /// Returns true if GetVehicleDocumentsByVehicleIdResponseStatus instances are equal
        /// </summary>
        /// <param name="other">Instance of GetVehicleDocumentsByVehicleIdResponseStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetVehicleDocumentsByVehicleIdResponseStatus other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    IsPtsAdded == other.IsPtsAdded ||
                    IsPtsAdded.Equals(other.IsPtsAdded)
                ) &&
                (
                    IsStsAdded == other.IsStsAdded ||
                    IsStsAdded.Equals(other.IsStsAdded)
                ) &&
                (
                    IsOsagoAdded == other.IsOsagoAdded ||
                    IsOsagoAdded.Equals(other.IsOsagoAdded)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + IsPtsAdded.GetHashCode();

                hashCode = hashCode * 59 + IsStsAdded.GetHashCode();

                hashCode = hashCode * 59 + IsOsagoAdded.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(
            GetVehicleDocumentsByVehicleIdResponseStatus left,
            GetVehicleDocumentsByVehicleIdResponseStatus right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(
            GetVehicleDocumentsByVehicleIdResponseStatus left,
            GetVehicleDocumentsByVehicleIdResponseStatus right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}