/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetVehicleDetailsByIdRes : IEquatable<GetVehicleDetailsByIdRes>
    {
        /// <summary>
        /// Уникальный идентификатор автомобиля.
        /// </summary>
        /// <value>Уникальный идентификатор автомобиля.</value>
        [Required]
        [DataMember(Name = "vehicleId", EmitDefaultValue = true)]
        public Guid VehicleId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public Status Status { get; set; }

        /// <summary>
        /// Марка автомобиля.
        /// </summary>
        /// <value>Марка автомобиля.</value>
        [Required]
        [DataMember(Name = "brand", EmitDefaultValue = false)]
        public string Brand { get; set; }

        /// <summary>
        /// Название модели автомобиля.
        /// </summary>
        /// <value>Название модели автомобиля.</value>
        [Required]
        [DataMember(Name = "carModel", EmitDefaultValue = false)]
        public string CarModel { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [Required]
        [DataMember(Name = "color", EmitDefaultValue = true)]
        public Color Color { get; set; }

        /// <summary>
        /// Государственный номер автомобиля.
        /// </summary>
        /// <value>Государственный номер автомобиля.</value>
        [Required]
        [DataMember(Name = "plateNumber", EmitDefaultValue = false)]
        public string PlateNumber { get; set; }

        /// <summary>
        /// Уровень топлива в процентах.
        /// </summary>
        /// <value>Уровень топлива в процентах.</value>
        [Required]
        [DataMember(Name = "fuelLevelPercents", EmitDefaultValue = true)]
        public int FuelLevelPercents { get; set; }

        /// <summary>
        /// VIN-номер автомобиля.
        /// </summary>
        /// <value>VIN-номер автомобиля.</value>
        [Required]
        [DataMember(Name = "vin", EmitDefaultValue = false)]
        public string Vin { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [Required]
        [DataMember(Name = "location", EmitDefaultValue = false)]
        public Location Location { get; set; }

        /// <summary>
        /// Стоимость аренды за минуту.
        /// </summary>
        /// <value>Стоимость аренды за минуту.</value>
        [Required]
        [DataMember(Name = "pricePerMin", EmitDefaultValue = true)]
        public double PricePerMin { get; set; }

        /// <summary>
        /// Стоимость аренды за час.
        /// </summary>
        /// <value>Стоимость аренды за час.</value>
        [Required]
        [DataMember(Name = "pricePerHour", EmitDefaultValue = true)]
        public double PricePerHour { get; set; }

        /// <summary>
        /// Стоимость аренды за день.
        /// </summary>
        /// <value>Стоимость аренды за день.</value>
        [Required]
        [DataMember(Name = "pricePerDay", EmitDefaultValue = true)]
        public double PricePerDay { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetVehicleDetailsByIdRes {\n");
            sb.Append("  VehicleId: ").Append(VehicleId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  CarModel: ").Append(CarModel).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  PlateNumber: ").Append(PlateNumber).Append("\n");
            sb.Append("  FuelLevelPercents: ").Append(FuelLevelPercents).Append("\n");
            sb.Append("  Vin: ").Append(Vin).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  PricePerMin: ").Append(PricePerMin).Append("\n");
            sb.Append("  PricePerHour: ").Append(PricePerHour).Append("\n");
            sb.Append("  PricePerDay: ").Append(PricePerDay).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetVehicleDetailsByIdRes)obj);
        }

        /// <summary>
        /// Returns true if GetVehicleDetailsByIdRes instances are equal
        /// </summary>
        /// <param name="other">Instance of GetVehicleDetailsByIdRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetVehicleDetailsByIdRes other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    VehicleId == other.VehicleId ||
                    VehicleId.Equals(other.VehicleId)
                ) &&
                (
                    Status == other.Status ||
                    Status.Equals(other.Status)
                ) &&
                (
                    Brand == other.Brand ||
                    Brand != null &&
                    Brand.Equals(other.Brand)
                ) &&
                (
                    CarModel == other.CarModel ||
                    CarModel != null &&
                    CarModel.Equals(other.CarModel)
                ) &&
                (
                    Color == other.Color ||
                    Color.Equals(other.Color)
                ) &&
                (
                    PlateNumber == other.PlateNumber ||
                    PlateNumber != null &&
                    PlateNumber.Equals(other.PlateNumber)
                ) &&
                (
                    FuelLevelPercents == other.FuelLevelPercents ||
                    FuelLevelPercents.Equals(other.FuelLevelPercents)
                ) &&
                (
                    Vin == other.Vin ||
                    Vin != null &&
                    Vin.Equals(other.Vin)
                ) &&
                (
                    Location == other.Location ||
                    Location != null &&
                    Location.Equals(other.Location)
                ) &&
                (
                    PricePerMin == other.PricePerMin ||
                    PricePerMin.Equals(other.PricePerMin)
                ) &&
                (
                    PricePerHour == other.PricePerHour ||
                    PricePerHour.Equals(other.PricePerHour)
                ) &&
                (
                    PricePerDay == other.PricePerDay ||
                    PricePerDay.Equals(other.PricePerDay)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + VehicleId.GetHashCode();

                hashCode = hashCode * 59 + Status.GetHashCode();
                if (Brand != null)
                    hashCode = hashCode * 59 + Brand.GetHashCode();
                if (CarModel != null)
                    hashCode = hashCode * 59 + CarModel.GetHashCode();

                hashCode = hashCode * 59 + Color.GetHashCode();
                if (PlateNumber != null)
                    hashCode = hashCode * 59 + PlateNumber.GetHashCode();

                hashCode = hashCode * 59 + FuelLevelPercents.GetHashCode();
                if (Vin != null)
                    hashCode = hashCode * 59 + Vin.GetHashCode();
                if (Location != null)
                    hashCode = hashCode * 59 + Location.GetHashCode();

                hashCode = hashCode * 59 + PricePerMin.GetHashCode();

                hashCode = hashCode * 59 + PricePerHour.GetHashCode();

                hashCode = hashCode * 59 + PricePerDay.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(GetVehicleDetailsByIdRes left, GetVehicleDetailsByIdRes right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetVehicleDetailsByIdRes left, GetVehicleDetailsByIdRes right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}