/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetVehiclesInSquareRes : IEquatable<GetVehiclesInSquareRes>
    {
        /// <summary>
        /// Список автомобилей в указанном регионе.
        /// </summary>
        /// <value>Список автомобилей в указанном регионе.</value>
        [Required]
        [DataMember(Name = "vehicles", EmitDefaultValue = false)]
        public List<VehicleInSquareShortView> Vehicles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetVehiclesInSquareRes {\n");
            sb.Append("  Vehicles: ").Append(Vehicles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GetVehiclesInSquareRes)obj);
        }

        /// <summary>
        /// Returns true if GetVehiclesInSquareRes instances are equal
        /// </summary>
        /// <param name="other">Instance of GetVehiclesInSquareRes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetVehiclesInSquareRes other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
            (
                Vehicles == other.Vehicles ||
                Vehicles != null &&
                other.Vehicles != null &&
                Vehicles.SequenceEqual(other.Vehicles)
            );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Vehicles != null)
                    hashCode = hashCode * 59 + Vehicles.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(GetVehiclesInSquareRes left, GetVehiclesInSquareRes right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetVehiclesInSquareRes left, GetVehiclesInSquareRes right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}