/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Model : IEquatable<Model>
    {
        /// <summary>
        /// Уникальный идентификатор модели.
        /// </summary>
        /// <value>Уникальный идентификатор модели.</value>
        [Required]
        [DataMember(Name = "modelId", EmitDefaultValue = true)]
        public Guid ModelId { get; set; }

        /// <summary>
        /// Марка автомобиля.
        /// </summary>
        /// <value>Марка автомобиля.</value>
        [Required]
        [DataMember(Name = "brand", EmitDefaultValue = false)]
        public string Brand { get; set; }

        /// <summary>
        /// Название модели автомобиля.
        /// </summary>
        /// <value>Название модели автомобиля.</value>
        [Required]
        [DataMember(Name = "carModel", EmitDefaultValue = false)]
        public string CarModel { get; set; }

        /// <summary>
        /// Год выпуска автомобиля.
        /// </summary>
        /// <value>Год выпуска автомобиля.</value>
        [DataMember(Name = "year", EmitDefaultValue = true)]
        public int? Year { get; set; }

        /// <summary>
        /// Стоимость аренды за минуту.
        /// </summary>
        /// <value>Стоимость аренды за минуту.</value>
        [DataMember(Name = "dailyRate", EmitDefaultValue = true)]
        public double? DailyRate { get; set; }

        /// <summary>
        /// Почасовая ставка аренды.
        /// </summary>
        /// <value>Почасовая ставка аренды.</value>
        [DataMember(Name = "hourlyRate", EmitDefaultValue = true)]
        public double? HourlyRate { get; set; }

        /// <summary>
        /// Ставка за пробег.
        /// </summary>
        /// <value>Ставка за пробег.</value>
        [DataMember(Name = "minuteRate", EmitDefaultValue = true)]
        public double? MinuteRate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Model {\n");
            sb.Append("  ModelId: ").Append(ModelId).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  CarModel: ").Append(CarModel).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  DailyRate: ").Append(DailyRate).Append("\n");
            sb.Append("  HourlyRate: ").Append(HourlyRate).Append("\n");
            sb.Append("  MinuteRate: ").Append(MinuteRate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Model)obj);
        }

        /// <summary>
        /// Returns true if Model instances are equal
        /// </summary>
        /// <param name="other">Instance of Model to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Model other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    ModelId == other.ModelId ||
                    ModelId.Equals(other.ModelId)
                ) &&
                (
                    Brand == other.Brand ||
                    Brand != null &&
                    Brand.Equals(other.Brand)
                ) &&
                (
                    CarModel == other.CarModel ||
                    CarModel != null &&
                    CarModel.Equals(other.CarModel)
                ) &&
                (
                    Year == other.Year ||
                    Year.Equals(other.Year)
                ) &&
                (
                    DailyRate == other.DailyRate ||
                    DailyRate.Equals(other.DailyRate)
                ) &&
                (
                    HourlyRate == other.HourlyRate ||
                    HourlyRate.Equals(other.HourlyRate)
                ) &&
                (
                    MinuteRate == other.MinuteRate ||
                    MinuteRate.Equals(other.MinuteRate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + ModelId.GetHashCode();
                if (Brand != null)
                    hashCode = hashCode * 59 + Brand.GetHashCode();
                if (CarModel != null)
                    hashCode = hashCode * 59 + CarModel.GetHashCode();

                hashCode = hashCode * 59 + Year.GetHashCode();

                hashCode = hashCode * 59 + DailyRate.GetHashCode();

                hashCode = hashCode * 59 + HourlyRate.GetHashCode();

                hashCode = hashCode * 59 + MinuteRate.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(Model left, Model right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Model left, Model right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}