/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Статус истечения срока действия ОСАГО: * `notExpiredUnspecified` - ОСАГО не истекло (значение по умолчанию) * `expired` - ОСАГО истекло 
    /// </summary>
    /// <value>Статус истечения срока действия ОСАГО: * `notExpiredUnspecified` - ОСАГО не истекло (значение по умолчанию) * `expired` - ОСАГО истекло </value>
    [TypeConverter(typeof(CustomEnumConverter<OsagoStatus>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OsagoStatus
    {
        /// <summary>
        /// Enum NotExpiredUnspecifiedEnum for notExpiredUnspecified
        /// </summary>
        [EnumMember(Value = "notExpiredUnspecified")]
        NotExpiredUnspecifiedEnum = 1,

        /// <summary>
        /// Enum ExpiredEnum for expired
        /// </summary>
        [EnumMember(Value = "expired")] ExpiredEnum = 2
    }
}