/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Статус аренды.
    /// </summary>
    /// <value>Статус аренды.</value>
    [TypeConverter(typeof(CustomEnumConverter<RentStatus>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RentStatus
    {
        /// <summary>
        /// Enum InProgressEnum for inProgress
        /// </summary>
        [EnumMember(Value = "inProgress")] InProgressEnum = 1,

        /// <summary>
        /// Enum CompletedEnum for completed
        /// </summary>
        [EnumMember(Value = "completed")] CompletedEnum = 2
    }
}