/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Роль работника в системе.
    /// </summary>
    /// <value>Роль работника в системе.</value>
    [TypeConverter(typeof(CustomEnumConverter<Role>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Role
    {
        /// <summary>
        /// Enum CustomerEnum for customer
        /// </summary>
        [EnumMember(Value = "customer")] CustomerEnum = 1,

        /// <summary>
        /// Enum AdminEnum for admin
        /// </summary>
        [EnumMember(Value = "admin")] AdminEnum = 2,

        /// <summary>
        /// Enum SupportEnum for support
        /// </summary>
        [EnumMember(Value = "support")] SupportEnum = 3,

        /// <summary>
        /// Enum MaintenanceEnum for maintenance
        /// </summary>
        [EnumMember(Value = "maintenance")] MaintenanceEnum = 4,

        /// <summary>
        /// Enum HrEnum for hr
        /// </summary>
        [EnumMember(Value = "hr")] HrEnum = 5
    }
}