/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Статус автомобиля.
    /// </summary>
    /// <value>Статус автомобиля.</value>
    [TypeConverter(typeof(CustomEnumConverter<Status>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status
    {
        /// <summary>
        /// Enum AddingInProgressEnum for addingInProgress
        /// </summary>
        [EnumMember(Value = "addingInProgress")]
        AddingInProgressEnum = 1,

        /// <summary>
        /// Enum AddedEnum for added
        /// </summary>
        [EnumMember(Value = "added")] AddedEnum = 2,

        /// <summary>
        /// Enum NotAddedEnum for notAdded
        /// </summary>
        [EnumMember(Value = "notAdded")] NotAddedEnum = 3,

        /// <summary>
        /// Enum ReadyForReleaseEnum for readyForRelease
        /// </summary>
        [EnumMember(Value = "readyForRelease")]
        ReadyForReleaseEnum = 4,

        /// <summary>
        /// Enum ReleasedUnspecifiedEnum for releasedUnspecified
        /// </summary>
        [EnumMember(Value = "releasedUnspecified")]
        ReleasedUnspecifiedEnum = 5,

        /// <summary>
        /// Enum OccupiedEnum for occupied
        /// </summary>
        [EnumMember(Value = "occupied")] OccupiedEnum = 6,

        /// <summary>
        /// Enum ServicedEnum for serviced
        /// </summary>
        [EnumMember(Value = "serviced")] ServicedEnum = 7,

        /// <summary>
        /// Enum DeletedEnum for deleted
        /// </summary>
        [EnumMember(Value = "deleted")] DeletedEnum = 8
    }
}