/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using OpenApiContractV1.Converters;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// Тип трансмиссии автомобиля.
    /// </summary>
    /// <value>Тип трансмиссии автомобиля.</value>
    [TypeConverter(typeof(CustomEnumConverter<TransmissionType>))]
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransmissionType
    {
        /// <summary>
        /// Enum ManualEnum for manual
        /// </summary>
        [EnumMember(Value = "manual")] ManualEnum = 1,

        /// <summary>
        /// Enum AutomaticEnum for automatic
        /// </summary>
        [EnumMember(Value = "automatic")] AutomaticEnum = 2
    }
}