/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpdateModelTariffReq : IEquatable<UpdateModelTariffReq>
    {
        /// <summary>
        /// Новая стоимость аренды за минуту.
        /// </summary>
        /// <value>Новая стоимость аренды за минуту.</value>
        [DataMember(Name = "pricePerMin", EmitDefaultValue = true)]
        public double? PricePerMin { get; set; }

        /// <summary>
        /// Новая стоимость аренды за час.
        /// </summary>
        /// <value>Новая стоимость аренды за час.</value>
        [DataMember(Name = "pricePerHour", EmitDefaultValue = true)]
        public double? PricePerHour { get; set; }

        /// <summary>
        /// Новая стоимость аренды за день.
        /// </summary>
        /// <value>Новая стоимость аренды за день.</value>
        [DataMember(Name = "pricePerDay", EmitDefaultValue = true)]
        public double? PricePerDay { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateModelTariffReq {\n");
            sb.Append("  PricePerMin: ").Append(PricePerMin).Append("\n");
            sb.Append("  PricePerHour: ").Append(PricePerHour).Append("\n");
            sb.Append("  PricePerDay: ").Append(PricePerDay).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdateModelTariffReq)obj);
        }

        /// <summary>
        /// Returns true if UpdateModelTariffReq instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateModelTariffReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateModelTariffReq other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    PricePerMin == other.PricePerMin ||
                    PricePerMin.Equals(other.PricePerMin)
                ) &&
                (
                    PricePerHour == other.PricePerHour ||
                    PricePerHour.Equals(other.PricePerHour)
                ) &&
                (
                    PricePerDay == other.PricePerDay ||
                    PricePerDay.Equals(other.PricePerDay)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + PricePerMin.GetHashCode();

                hashCode = hashCode * 59 + PricePerHour.GetHashCode();

                hashCode = hashCode * 59 + PricePerDay.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(UpdateModelTariffReq left, UpdateModelTariffReq right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdateModelTariffReq left, UpdateModelTariffReq right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}