/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpdatePasswordRequest : IEquatable<UpdatePasswordRequest>
    {
        /// <summary>
        /// Новый пароль.
        /// </summary>
        /// <value>Новый пароль.</value>
        /* <example>new-password</example> */
        [Required]
        [DataMember(Name = "newPassword", EmitDefaultValue = false)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Email аккаунта.
        /// </summary>
        /// <value>Email аккаунта.</value>
        /* <example>example@example.com</example> */
        [Required]
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// Токен для сброса пароля.
        /// </summary>
        /// <value>Токен для сброса пароля.</value>
        /* <example>123e4567-e89b-12d3-a456-426614174000</example> */
        [Required]
        [DataMember(Name = "resetToken", EmitDefaultValue = false)]
        public string ResetToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdatePasswordRequest {\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  ResetToken: ").Append(ResetToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdatePasswordRequest)obj);
        }

        /// <summary>
        /// Returns true if UpdatePasswordRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdatePasswordRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdatePasswordRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    NewPassword == other.NewPassword ||
                    NewPassword != null &&
                    NewPassword.Equals(other.NewPassword)
                ) &&
                (
                    Email == other.Email ||
                    Email != null &&
                    Email.Equals(other.Email)
                ) &&
                (
                    ResetToken == other.ResetToken ||
                    ResetToken != null &&
                    ResetToken.Equals(other.ResetToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (NewPassword != null)
                    hashCode = hashCode * 59 + NewPassword.GetHashCode();
                if (Email != null)
                    hashCode = hashCode * 59 + Email.GetHashCode();
                if (ResetToken != null)
                    hashCode = hashCode * 59 + ResetToken.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(UpdatePasswordRequest left, UpdatePasswordRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdatePasswordRequest left, UpdatePasswordRequest right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}