/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Vehicle : IEquatable<Vehicle>
    {
        /// <summary>
        /// Уникальный идентификатор автомобиля.
        /// </summary>
        /// <value>Уникальный идентификатор автомобиля.</value>
        [Required]
        [DataMember(Name = "vehicleId", EmitDefaultValue = true)]
        public Guid VehicleId { get; set; }

        /// <summary>
        /// Уникальный идентификатор модели автомобиля.
        /// </summary>
        /// <value>Уникальный идентификатор модели автомобиля.</value>
        [Required]
        [DataMember(Name = "modelId", EmitDefaultValue = true)]
        public Guid ModelId { get; set; }

        /// <summary>
        /// Государственный номер автомобиля.
        /// </summary>
        /// <value>Государственный номер автомобиля.</value>
        [Required]
        [DataMember(Name = "licensePlate", EmitDefaultValue = false)]
        public string LicensePlate { get; set; }

        /// <summary>
        /// Цвет автомобиля.
        /// </summary>
        /// <value>Цвет автомобиля.</value>
        [Required]
        [DataMember(Name = "color", EmitDefaultValue = false)]
        public string Color { get; set; }

        /// <summary>
        /// Пробег автомобиля в километрах.
        /// </summary>
        /// <value>Пробег автомобиля в километрах.</value>
        [Required]
        [DataMember(Name = "mileage", EmitDefaultValue = true)]
        public int Mileage { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [Required]
        [DataMember(Name = "status", EmitDefaultValue = true)]
        public Status Status { get; set; }

        /// <summary>
        /// Gets or Sets CurrentLocation
        /// </summary>
        [Required]
        [DataMember(Name = "currentLocation", EmitDefaultValue = false)]
        public Location CurrentLocation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Vehicle {\n");
            sb.Append("  VehicleId: ").Append(VehicleId).Append("\n");
            sb.Append("  ModelId: ").Append(ModelId).Append("\n");
            sb.Append("  LicensePlate: ").Append(LicensePlate).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Mileage: ").Append(Mileage).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CurrentLocation: ").Append(CurrentLocation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Vehicle)obj);
        }

        /// <summary>
        /// Returns true if Vehicle instances are equal
        /// </summary>
        /// <param name="other">Instance of Vehicle to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Vehicle other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    VehicleId == other.VehicleId ||
                    VehicleId.Equals(other.VehicleId)
                ) &&
                (
                    ModelId == other.ModelId ||
                    ModelId.Equals(other.ModelId)
                ) &&
                (
                    LicensePlate == other.LicensePlate ||
                    LicensePlate != null &&
                    LicensePlate.Equals(other.LicensePlate)
                ) &&
                (
                    Color == other.Color ||
                    Color != null &&
                    Color.Equals(other.Color)
                ) &&
                (
                    Mileage == other.Mileage ||
                    Mileage.Equals(other.Mileage)
                ) &&
                (
                    Status == other.Status ||
                    Status.Equals(other.Status)
                ) &&
                (
                    CurrentLocation == other.CurrentLocation ||
                    CurrentLocation != null &&
                    CurrentLocation.Equals(other.CurrentLocation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + VehicleId.GetHashCode();

                hashCode = hashCode * 59 + ModelId.GetHashCode();
                if (LicensePlate != null)
                    hashCode = hashCode * 59 + LicensePlate.GetHashCode();
                if (Color != null)
                    hashCode = hashCode * 59 + Color.GetHashCode();

                hashCode = hashCode * 59 + Mileage.GetHashCode();

                hashCode = hashCode * 59 + Status.GetHashCode();
                if (CurrentLocation != null)
                    hashCode = hashCode * 59 + CurrentLocation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(Vehicle left, Vehicle right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Vehicle left, Vehicle right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}