/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenApiContractV1.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VehicleShortView : IEquatable<VehicleShortView>
    {
        /// <summary>
        /// Уникальный идентификатор автомобиля.
        /// </summary>
        /// <value>Уникальный идентификатор автомобиля.</value>
        [Required]
        [DataMember(Name = "vehicleId", EmitDefaultValue = true)]
        public Guid VehicleId { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [Required]
        [DataMember(Name = "color", EmitDefaultValue = true)]
        public Color Color { get; set; }

        /// <summary>
        /// Марка автомобиля.
        /// </summary>
        /// <value>Марка автомобиля.</value>
        [Required]
        [DataMember(Name = "brand", EmitDefaultValue = false)]
        public string Brand { get; set; }

        /// <summary>
        /// Название модели автомобиля.
        /// </summary>
        /// <value>Название модели автомобиля.</value>
        [Required]
        [DataMember(Name = "carModel", EmitDefaultValue = false)]
        public string CarModel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VehicleShortView {\n");
            sb.Append("  VehicleId: ").Append(VehicleId).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  CarModel: ").Append(CarModel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VehicleShortView)obj);
        }

        /// <summary>
        /// Returns true if VehicleShortView instances are equal
        /// </summary>
        /// <param name="other">Instance of VehicleShortView to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VehicleShortView other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    VehicleId == other.VehicleId ||
                    VehicleId.Equals(other.VehicleId)
                ) &&
                (
                    Color == other.Color ||
                    Color.Equals(other.Color)
                ) &&
                (
                    Brand == other.Brand ||
                    Brand != null &&
                    Brand.Equals(other.Brand)
                ) &&
                (
                    CarModel == other.CarModel ||
                    CarModel != null &&
                    CarModel.Equals(other.CarModel)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + VehicleId.GetHashCode();

                hashCode = hashCode * 59 + Color.GetHashCode();
                if (Brand != null)
                    hashCode = hashCode * 59 + Brand.GetHashCode();
                if (CarModel != null)
                    hashCode = hashCode * 59 + CarModel.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(VehicleShortView left, VehicleShortView right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VehicleShortView left, VehicleShortView right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}