/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using OpenApiContractV1.Attributes;
using OpenApiContractV1.Models;
using Swashbuckle.AspNetCore.Annotations;

namespace OpenApiContractV1.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class IdentityApiController : ControllerBase
    {
        /// <summary>
        /// Аутентификация аккаунта
        /// </summary>
        /// <param name="authenticateRequest"></param>
        /// <response code="200">Успешная операция</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        /// <response code="404">Аккаунт с таким идентификатором не найден</response>
        [HttpPost]
        [Route("/v1.0/identity/authenticate")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("Authenticate")]
        [SwaggerResponse(statusCode: 200, type: typeof(AuthenticateResponse), description: "Успешная операция")]
        public abstract Task<IActionResult> Authenticate([FromBody] AuthenticateRequest authenticateRequest);

        /// <summary>
        /// Подтверждение email аккаунта
        /// </summary>
        /// <param name="accountId">Идентификатор аккаунта</param>
        /// <param name="confirmationToken">Токен подтверждения</param>
        /// <response code="200">Успешная операция</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        /// <response code="404">Токен подтверждения не найден</response>
        [HttpPost]
        [Route("/v1.0/identity/{accountId}/confirmation-token/{confirmationToken}/confirm")]
        [ValidateModelState]
        [SwaggerOperation("ConfirmAccountEmail")]
        public abstract Task<IActionResult> ConfirmAccountEmail(
            [FromRoute(Name = "accountId")] [Required] Guid accountId,
            [FromRoute(Name = "confirmationToken")] [Required] string confirmationToken);

        /// <summary>
        /// Создание аккаунта
        /// </summary>
        /// <param name="createRequest"></param>
        /// <response code="201">Аккаунт успешно создан</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        [HttpPost]
        [Route("/v1.0/identity/account/create")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateAccount")]
        [SwaggerResponse(statusCode: 201, type: typeof(CreateResponse), description: "Аккаунт успешно создан")]
        public abstract Task<IActionResult> CreateAccount([FromBody] CreateRequest createRequest);

        /// <summary>
        /// Восстановление пароля
        /// </summary>
        /// <param name="request"></param>
        /// <response code="200">Успешная операция</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        /// <response code="404">Аккаунт с таким идентификатором не найден</response>
        [HttpPost]
        [Route("/v1.0/identity/account/recover-password")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("RecoverPassword")]
        public abstract Task<IActionResult> RecoverPassword([FromBody] RecoverPasswordRequest request);

        /// <summary>
        /// Обновление токена доступа
        /// </summary>
        /// <param name="refreshAccessTokenRequest"></param>
        /// <response code="200">Успешная операция</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        /// <response code="404">Refresh token с таким идентификатором не найден</response>
        [HttpPost]
        [Route("/v1.0/identity/refresh-access-token")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("RefreshAccessToken")]
        [SwaggerResponse(statusCode: 200, type: typeof(RefreshAccessTokenResponse), description: "Успешная операция")]
        public abstract Task<IActionResult> RefreshAccessToken(
            [FromBody] RefreshAccessTokenRequest refreshAccessTokenRequest);

        /// <summary>
        /// Обновление пароля
        /// </summary>
        /// <param name="updatePasswordRequest"></param>
        /// <response code="200">Успешная операция</response>
        /// <response code="500">Внутренняя ошибка сервера</response>
        /// <response code="404">Аккаунт с таким идентификатором не найден</response>
        [HttpPost]
        [Route("/v1.0/identity/account/update-password")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("UpdatePassword")]
        public abstract Task<IActionResult> UpdatePassword([FromBody] UpdatePasswordRequest updatePasswordRequest);
    }
}