/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using OpenApiContractV1.Attributes;
using OpenApiContractV1.Models;
using Swashbuckle.AspNetCore.Annotations;

namespace OpenApiContractV1.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ModelApiController : ControllerBase
    {
        /// <summary>
        /// Add New Model
        /// </summary>
        /// <remarks>Добавляет новую модель автомобиля.</remarks>
        /// <param name="addModelReq"></param>
        /// <response code="200">Модель успешно добавлена.</response>
        /// <response code="400">Некорректный запрос.</response>
        [HttpPost]
        [Route("/v1.0/models")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("AddModel")]
        [SwaggerResponse(statusCode: 200, type: typeof(AddModelRes), description: "Модель успешно добавлена.")]
        public abstract Task<IActionResult> AddModel([FromBody] AddModelReq addModelReq);

        /// <summary>
        /// Get All Models
        /// </summary>
        /// <remarks>Получает список всех доступных моделей автомобилей.</remarks>
        /// <param name="page">Номер страницы для пагинации.</param>
        /// <param name="pageSize">Количество элементов на странице для пагинации.</param>
        /// <response code="200">Успешный ответ со списком моделей.</response>
        [HttpGet]
        [Route("/v1.0/models")]
        [ValidateModelState]
        [SwaggerOperation("GetAllModels")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetAllModelsRes),
            description: "Успешный ответ со списком моделей.")]
        public abstract Task<IActionResult> GetAllModels(
            [FromQuery(Name = "page")] int? page,
            [FromQuery(Name = "pageSize")] int? pageSize);

        /// <summary>
        /// Get Model by ID
        /// </summary>
        /// <remarks>Получает информацию о модели автомобиля по её уникальному идентификатору.</remarks>
        /// <param name="modelId">Уникальный идентификатор модели.</param>
        /// <response code="200">Успешный ответ с информацией о модели.</response>
        /// <response code="404">Модель с указанным ID не найдена.</response>
        [HttpGet]
        [Route("/v1.0/models/{modelId}")]
        [ValidateModelState]
        [SwaggerOperation("GetModelById")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetModelByIdRes),
            description: "Успешный ответ с информацией о модели.")]
        public abstract Task<IActionResult> GetModelById([FromRoute(Name = "modelId")] [Required] Guid modelId);

        /// <summary>
        /// Update Model Category
        /// </summary>
        /// <remarks>Обновляет категорию модели автомобиля.</remarks>
        /// <param name="modelId">Уникальный идентификатор модели.</param>
        /// <param name="updateModelCategoryReq"></param>
        /// <response code="200">Категория модели успешно обновлена.</response>
        /// <response code="400">Некорректный запрос.</response>
        /// <response code="404">Модель с указанным ID не найдена.</response>
        [HttpPatch]
        [Route("/v1.0/models/{modelId}/category")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("UpdateModelCategory")]
        public abstract Task<IActionResult> UpdateModelCategory(
            [FromRoute(Name = "modelId")] [Required] Guid modelId,
            [FromBody] UpdateModelCategoryReq updateModelCategoryReq);

        /// <summary>
        /// Update Model Tariff
        /// </summary>
        /// <remarks>Обновляет тарифы модели автомобиля.</remarks>
        /// <param name="modelId">Уникальный идентификатор модели.</param>
        /// <param name="updateModelTariffReq"></param>
        /// <response code="200">Тарифы модели успешно обновлены.</response>
        /// <response code="400">Некорректный запрос.</response>
        /// <response code="404">Модель с указанным ID не найдена.</response>
        [HttpPatch]
        [Route("/v1.0/models/{modelId}/tariff")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("UpdateModelTariff")]
        public abstract Task<IActionResult> UpdateModelTariff(
            [FromRoute(Name = "modelId")] [Required] Guid modelId,
            [FromBody] UpdateModelTariffReq updateModelTariffReq);
    }
}