/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using OpenApiContractV1.Attributes;
using OpenApiContractV1.Models;
using Swashbuckle.AspNetCore.Annotations;

namespace OpenApiContractV1.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class VehicleCheckApiController : ControllerBase
    {
        /// <summary>
        /// Get All Checks for Considerate Review
        /// </summary>
        /// <remarks>Получает список всех проверок, требующих внимательного рассмотрения.</remarks>
        /// <param name="page">Номер страницы для пагинации.</param>
        /// <param name="pageSize">Количество элементов на странице для пагинации.</param>
        /// <response code="200">Успешный ответ со списком проверок.</response>
        [HttpGet]
        [Route("/v1.0/checks/for-review")]
        [ValidateModelState]
        [SwaggerOperation("GetAllChecksForConsiderateReview")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetAllChecksForConsiderateReviewResponse),
            description: "Успешный ответ со списком проверок.")]
        public abstract Task<IActionResult> GetAllChecksForConsiderateReview(
            [FromQuery(Name = "page")] int? page,
            [FromQuery(Name = "pageSize")] int? pageSize);

        /// <summary>
        /// Get Check by ID
        /// </summary>
        /// <remarks>Получает информацию о проверке по её уникальному идентификатору.</remarks>
        /// <param name="checkId">Уникальный идентификатор проверки.</param>
        /// <response code="200">Успешный ответ с информацией о проверке.</response>
        /// <response code="404">Проверка с указанным ID не найдена.</response>
        [HttpGet]
        [Route("/v1.0/checks/{checkId}")]
        [ValidateModelState]
        [SwaggerOperation("GetCheckById")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetCheckByIdResponse),
            description: "Успешный ответ с информацией о проверке.")]
        public abstract Task<IActionResult> GetCheckById([FromRoute(Name = "checkId")] [Required] Guid checkId);
    }
}