/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using OpenApiContractV1.Attributes;
using OpenApiContractV1.Models;
using Swashbuckle.AspNetCore.Annotations;

namespace OpenApiContractV1.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class VehicleApiController : ControllerBase
    {
        /// <summary>
        /// Add New Vehicle
        /// </summary>
        /// <remarks>Добавляет новый автомобиль в автопарк.</remarks>
        /// <param name="addVehicleReq"></param>
        /// <response code="200">Автомобиль успешно добавлен.</response>
        /// <response code="400">Некорректный запрос.</response>
        [HttpPost]
        [Route("/v1.0/vehicles")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("AddVehicle")]
        [SwaggerResponse(statusCode: 200, type: typeof(AddVehicleRes), description: "Автомобиль успешно добавлен.")]
        public abstract Task<IActionResult> AddVehicle([FromBody] AddVehicleReq addVehicleReq);

        /// <summary>
        /// Delete Vehicle
        /// </summary>
        /// <remarks>Удаляет автомобиль из автопарка.</remarks>
        /// <param name="vehicleId">Уникальный идентификатор автомобиля.</param>
        /// <response code="200">Автомобиль успешно удален.</response>
        /// <response code="404">Автомобиль с указанным ID не найден.</response>
        [HttpDelete]
        [Route("/v1.0/vehicles/{vehicleId}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteVehicle")]
        public abstract Task<IActionResult> DeleteVehicle([FromRoute(Name = "vehicleId")] [Required] Guid vehicleId);

        /// <summary>
        /// Get All Vehicles
        /// </summary>
        /// <remarks>Получает список всех автомобилей с возможностью фильтрации по статусу.</remarks>
        /// <param name="filteringStatus">Статус для фильтрации автомобилей.</param>
        /// <param name="page">Номер страницы для пагинации.</param>
        /// <param name="pageSize">Количество элементов на странице для пагинации.</param>
        /// <response code="200">Успешный ответ со списком автомобилей.</response>
        [HttpGet]
        [Route("/v1.0/vehicles")]
        [ValidateModelState]
        [SwaggerOperation("GetAllVehicles")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetAllVehiclesRes),
            description: "Успешный ответ со списком автомобилей.")]
        public abstract Task<IActionResult> GetAllVehicles(
            [FromQuery(Name = "filteringStatus")] [Required()] Status filteringStatus,
            [FromQuery(Name = "page")] int? page,
            [FromQuery(Name = "pageSize")] int? pageSize);

        /// <summary>
        /// Get Vehicle by ID
        /// </summary>
        /// <remarks>Получает краткую информацию об автомобиле по его уникальному идентификатору.</remarks>
        /// <param name="vehicleId">Уникальный идентификатор автомобиля.</param>
        /// <response code="200">Успешный ответ с краткой информацией об автомобиле.</response>
        /// <response code="404">Автомобиль с указанным ID не найден.</response>
        [HttpGet]
        [Route("/v1.0/vehicles/{vehicleId}")]
        [ValidateModelState]
        [SwaggerOperation("GetVehicleById")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetVehicleByIdRes),
            description: "Успешный ответ с краткой информацией об автомобиле.")]
        public abstract Task<IActionResult> GetVehicleById([FromRoute(Name = "vehicleId")] [Required] Guid vehicleId);

        /// <summary>
        /// Get Vehicle Details by ID
        /// </summary>
        /// <remarks>Получает подробную информацию об автомобиле по его уникальному идентификатору.</remarks>
        /// <param name="vehicleId">Уникальный идентификатор автомобиля.</param>
        /// <response code="200">Успешный ответ с подробной информацией об автомобиле.</response>
        /// <response code="404">Автомобиль с указанным ID не найден.</response>
        [HttpGet]
        [Route("/v1.0/vehicles/{vehicleId}/details")]
        [ValidateModelState]
        [SwaggerOperation("GetVehicleDetailsById")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetVehicleDetailsByIdRes),
            description: "Успешный ответ с подробной информацией об автомобиле.")]
        public abstract Task<IActionResult> GetVehicleDetailsById(
            [FromRoute(Name = "vehicleId")] [Required] Guid vehicleId);

        /// <summary>
        /// Get Vehicles in Square
        /// </summary>
        /// <remarks>Получает список автомобилей, находящихся в заданном квадратном регионе.</remarks>
        /// <param name="getVehiclesInSquareReq"></param>
        /// <response code="200">Успешный ответ со списком автомобилей в указанном регионе.</response>
        /// <response code="400">Некорректные координаты или статус.</response>
        [HttpPost]
        [Route("/v1.0/vehicles/in-square")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("GetVehiclesInSquare")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetVehiclesInSquareRes),
            description: "Успешный ответ со списком автомобилей в указанном регионе.")]
        public abstract Task<IActionResult> GetVehiclesInSquare(
            [FromBody] GetVehiclesInSquareReq getVehiclesInSquareReq);

        /// <summary>
        /// Mark Vehicle as Readied for Release
        /// </summary>
        /// <remarks>Отмечает автомобиль как подготовленный к выпуску.</remarks>
        /// <param name="vehicleId">Уникальный идентификатор автомобиля.</param>
        /// <response code="200">Автомобиль успешно отмечен как подготовленный к выпуску.</response>
        /// <response code="404">Автомобиль с указанным ID не найден.</response>
        [HttpPost]
        [Route("/v1.0/vehicles/{vehicleId}/mark-as-readied-for-release")]
        [ValidateModelState]
        [SwaggerOperation("MarkAsReadiedForReleaseVehicle")]
        public abstract Task<IActionResult> MarkAsReadiedForReleaseVehicle(
            [FromRoute(Name = "vehicleId")] [Required] Guid vehicleId);

        /// <summary>
        /// Release Vehicle
        /// </summary>
        /// <remarks>Выпускает автомобиль в аренду.</remarks>
        /// <param name="vehicleId">Уникальный идентификатор автомобиля.</param>
        /// <response code="200">Автомобиль успешно выпущен.</response>
        /// <response code="404">Автомобиль с указанным ID не найден.</response>
        [HttpPost]
        [Route("/v1.0/vehicles/{vehicleId}/release")]
        [ValidateModelState]
        [SwaggerOperation("ReleaseVehicle")]
        public abstract Task<IActionResult> ReleaseVehicle([FromRoute(Name = "vehicleId")] [Required] Guid vehicleId);

        /// <summary>
        /// Send Vehicle to Service
        /// </summary>
        /// <remarks>Отправляет автомобиль на обслуживание.</remarks>
        /// <param name="vehicleId">Уникальный идентификатор автомобиля.</param>
        /// <response code="200">Автомобиль успешно отправлен на обслуживание.</response>
        /// <response code="404">Автомобиль с указанным ID не найден.</response>
        [HttpPost]
        [Route("/v1.0/vehicles/{vehicleId}/send-to-service")]
        [ValidateModelState]
        [SwaggerOperation("SendToServiceVehicle")]
        public abstract Task<IActionResult> SendToServiceVehicle(
            [FromRoute(Name = "vehicleId")] [Required] Guid vehicleId);
    }
}