/*
 * Employee BFF
 *
 * BFF для работы с приложениями сотрудников
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using OpenApiContractV1.Attributes;
using OpenApiContractV1.Models;
using Swashbuckle.AspNetCore.Annotations;

namespace OpenApiContractV1.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class VehicleDocumentsApiController : ControllerBase
    {
        /// <summary>
        /// Add OSAGO
        /// </summary>
        /// <remarks>Добавляет информацию об ОСАГО для документов на автомобиль.</remarks>
        /// <param name="vehicleDocumentsId">Уникальный идентификатор комплекта документов на автомобиль.</param>
        /// <param name="addOsagoRequest"></param>
        /// <response code="200">Информация об ОСАГО успешно добавлена.</response>
        /// <response code="400">Некорректный запрос.</response>
        /// <response code="404">Документы на автомобиль с указанным ID не найдены.</response>
        [HttpPost]
        [Route("/v1.0/vehicle-documents/{vehicleDocumentsId}/osago")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("AddOsago")]
        public abstract Task<IActionResult> AddOsago(
            [FromRoute(Name = "vehicleDocumentsId")] [Required] Guid vehicleDocumentsId,
            [FromBody] AddOsagoRequest addOsagoRequest);

        /// <summary>
        /// Add PTS
        /// </summary>
        /// <remarks>Добавляет информацию о ПТС для документов на автомобиль.</remarks>
        /// <param name="vehicleDocumentsId">Уникальный идентификатор комплекта документов на автомобиль.</param>
        /// <param name="addPtsRequest"></param>
        /// <response code="200">Информация о ПТС успешно добавлена.</response>
        /// <response code="400">Некорректный запрос.</response>
        /// <response code="404">Документы на автомобиль с указанным ID не найдены.</response>
        [HttpPost]
        [Route("/v1.0/vehicle-documents/{vehicleDocumentsId}/pts")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("AddPts")]
        public abstract Task<IActionResult> AddPts(
            [FromRoute(Name = "vehicleDocumentsId")] [Required] Guid vehicleDocumentsId,
            [FromBody] AddPtsRequest addPtsRequest);

        /// <summary>
        /// Add STS
        /// </summary>
        /// <remarks>Добавляет информацию о СТС для документов на автомобиль.</remarks>
        /// <param name="vehicleDocumentsId">Уникальный идентификатор комплекта документов на автомобиль.</param>
        /// <param name="addStsRequest"></param>
        /// <response code="200">Информация о СТС успешно добавлена.</response>
        /// <response code="400">Некорректный запрос.</response>
        /// <response code="404">Документы на автомобиль с указанным ID не найдены.</response>
        [HttpPost]
        [Route("/v1.0/vehicle-documents/{vehicleDocumentsId}/sts")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("AddSts")]
        public abstract Task<IActionResult> AddSts(
            [FromRoute(Name = "vehicleDocumentsId")] [Required] Guid vehicleDocumentsId,
            [FromBody] AddStsRequest addStsRequest);

        /// <summary>
        /// Get OSAGO by Vehicle Documents ID
        /// </summary>
        /// <remarks>Получает информацию об ОСАГО по идентификатору комплекта документов на автомобиль.</remarks>
        /// <param name="vehicleDocumentsId">Уникальный идентификатор комплекта документов на автомобиль.</param>
        /// <response code="200">Успешный ответ с информацией об ОСАГО.</response>
        /// <response code="404">Информация об ОСАГО или документы на автомобиль не найдены.</response>
        [HttpGet]
        [Route("/v1.0/vehicle-documents/{vehicleDocumentsId}/osago")]
        [ValidateModelState]
        [SwaggerOperation("GetOsagoByVehicleDocumentsId")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetOsagoByVehicleDocumentsIdResponse),
            description: "Успешный ответ с информацией об ОСАГО.")]
        public abstract Task<IActionResult> GetOsagoByVehicleDocumentsId(
            [FromRoute(Name = "vehicleDocumentsId")] [Required] Guid vehicleDocumentsId);

        /// <summary>
        /// Get PTS by Vehicle Documents ID
        /// </summary>
        /// <remarks>Получает информацию о ПТС по идентификатору комплекта документов на автомобиль.</remarks>
        /// <param name="vehicleDocumentsId">Уникальный идентификатор комплекта документов на автомобиль.</param>
        /// <response code="200">Успешный ответ с информацией о ПТС.</response>
        /// <response code="404">Информация о ПТС или документы на автомобиль не найдены.</response>
        [HttpGet]
        [Route("/v1.0/vehicle-documents/{vehicleDocumentsId}/pts")]
        [ValidateModelState]
        [SwaggerOperation("GetPtsByVehicleDocumentsId")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetPtsByVehicleDocumentsIdResponse),
            description: "Успешный ответ с информацией о ПТС.")]
        public abstract Task<IActionResult> GetPtsByVehicleDocumentsId(
            [FromRoute(Name = "vehicleDocumentsId")] [Required] Guid vehicleDocumentsId);

        /// <summary>
        /// Get STS by Vehicle Documents ID
        /// </summary>
        /// <remarks>Получает информацию о СТС по идентификатору комплекта документов на автомобиль.</remarks>
        /// <param name="vehicleDocumentsId">Уникальный идентификатор комплекта документов на автомобиль.</param>
        /// <response code="200">Успешный ответ с информацией о СТС.</response>
        /// <response code="404">Информация о СТС или документы на автомобиль не найдены.</response>
        [HttpGet]
        [Route("/v1.0/vehicle-documents/{vehicleDocumentsId}/sts")]
        [ValidateModelState]
        [SwaggerOperation("GetStsByVehicleDocumentsId")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetStsByVehicleDocumentsIdResponse),
            description: "Успешный ответ с информацией о СТС.")]
        public abstract Task<IActionResult> GetStsByVehicleDocumentsId(
            [FromRoute(Name = "vehicleDocumentsId")] [Required] Guid vehicleDocumentsId);

        /// <summary>
        /// Get Vehicle Documents by Vehicle ID
        /// </summary>
        /// <remarks>Получает статус наличия документов (ПТС, СТС, ОСАГО) для указанного автомобиля.</remarks>
        /// <param name="vehicleId">Уникальный идентификатор автомобиля.</param>
        /// <response code="200">Успешный ответ со статусом документов автомобиля.</response>
        /// <response code="404">Документы для указанного автомобиля не найдены.</response>
        [HttpGet]
        [Route("/v1.0/vehicle-documents")]
        [ValidateModelState]
        [SwaggerOperation("GetVehicleDocumentsByVehicleId")]
        [SwaggerResponse(statusCode: 200, type: typeof(GetVehicleDocumentsByVehicleIdResponse),
            description: "Успешный ответ со статусом документов автомобиля.")]
        public abstract Task<IActionResult> GetVehicleDocumentsByVehicleId(
            [FromQuery(Name = "vehicleId")] [Required()] Guid vehicleId);
    }
}